# Generated by Django 5.1.1 on 2024-11-08 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_certificates_cert_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.experience'),
        ),
    ]
