# Generated by Django 5.1.1 on 2024-11-16 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_offers_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.person')),
            ],
        ),
    ]
