# Generated by Django 5.1.1 on 2024-11-17 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_skilldescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilldescription',
            name='owner',
        ),
        migrations.AddField(
            model_name='skilldescription',
            name='skill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.skills'),
            preserve_default=False,
        ),
    ]
