# Generated by Django 4.2.16 on 2024-12-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_skilldescription_owner_skilldescription_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
